language: java
jdk:
  - openjdk7
  - oraclejdk7
notifications:
    email: false
    irc:
      channels:
        - "irc.wma.im#minecraft-dev"
      template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url} - Build Time : %{duration}"
branches:
  only:
    - development
