language: java
jdk:
  - openjdk7
  - oraclejdk7
notifications:
    email: false
    irc: "irc.wma.im#minecraft-dev"
      template:
        - "%{repository} (%{commit}) : %{message} %{foo} "
        - "Build details: %{build_url}"
branches:
  only:
    - development
