name: BukkitIRCd
version: 1.2
description: 'Powerful IRC plugin for Bukkit. Can be used on its own or alongside an InspIRCd server.'
website: 'http://wma.im'
main: com.Jdbye.BukkitIRCd.BukkitIRCdPlugin
softdepend:
  - dynmap
authors:
  - Jdbye
  - WizardCM
  - Mu5tank05
  - glguy
  - Monofraps
  - ron975
commands:
  irc:
    description: 'NoCheatPlus command(s).'
    usage: "BukkitIRCd commands list:\n/irclist - Lists the online users on IRC.\n/irckick - Kick a user from IRC.\n/ircban - Ban a user from IRC via their host, ip, ident, nick or a full hostmask.\n/ircunban - Unban a user from IRC by their IP or full hostmask.\n/ircwhois - Perform a lookup on an IRC user.\n/ircmsg - Private message a user on IRC.\n/ircreply - Reply to the last IRC private message you received.\n/irctopic - Change the IRC topic for the main channel\n/irclink - Attempt to link to the remote server if in linking mode but not currently linked.\n/ircreload - Reload the plugin configuration and MOTD, and restart the IRC server/link.\n/rawsend - Sends a raw server command to the linked server, if enabled. Only usable from console.\n"
  ircban:
    aliases:
      - iban
    description: 'Ban a user from IRC via their host, ip, ident, nick or a full hostmask.'
    permission: bukkitircd.ban
    usage: '/<command> (host/ip/ident/nick) nick/ip/fullhost (reason)'
  irckick:
    aliases:
      - ikick
    description: 'Kick a user from IRC.'
    permission: bukkitircd.kick
    usage: '/<command> nick (reason)'
  irclink:
    aliases:
      - ilink
    description: 'Attempt to link to the remote server if in linking mode but not currently linked.'
    permission: bukkitircd.link
    usage: /<command>
  irclist:
    aliases:
      - ilist
    description: 'Lists the online users on IRC.'
    permission: bukkitircd.list
    usage: /<command>
  ircmsg:
    aliases:
      - imsg
      - im
      - itell
    description: 'Private message a user on IRC.'
    permission: bukkitircd.msg
    usage: '/<command> nick message'
  ircreload:
    aliases:
      - ireload
    description: 'Reload the plugin configuration and MOTD, and restart the IRC server/link.'
    permission: bukkitircd.reload
    usage: /<command>
  ircreply:
    aliases:
      - ireply
      - ir
    description: 'Reply to the last IRC private message you received.'
    permission: bukkitircd.reply
    usage: '/<command> message'
  irctopic:
    aliases:
      - itopic
    description: 'Change the IRC topic for the main channel'
    permission: bukkitircd.topic
    usage: '/<command> newtopic'
  ircunban:
    aliases:
      - iunban
    description: 'Unban a user from IRC by their IP or full hostmask.'
    permission: bukkitircd.unban
    usage: '/<command> ip/fullhost'
  ircwhois:
    aliases:
      - iwhois
    description: 'Perform a lookup on an IRC user.'
    permission: bukkitircd.whois
    usage: '/<command> nick'
  rawsend:
    description: 'Sends a raw server command to the linked server, if enabled. Only usable from console.'
    usage: '/<command> command'
permissions:
  'bukkitircd.*':
    children:
      bukkitircd.ban: true
      bukkitircd.kick: true
      bukkitircd.link: true
      bukkitircd.list: true
      bukkitircd.msg: true
      bukkitircd.reload: true
      bukkitircd.reply: true
      bukkitircd.topic: true
      bukkitircd.unban: true
      bukkitircd.whois: true
    description: 'Allows you to use every /irc command'
  bukkitircd.ban:
    default: op
    description: 'Allows you to use the /ircban command'
  bukkitircd.kick:
    default: op
    description: 'Allows you to use the /irckick command'
  bukkitircd.link:
    default: op
    description: 'Allows you to use the /irclink command'
  bukkitircd.list:
    default: op
    description: 'Allows you to use the /irclist command'
  'bukkitircd.mode.*':
    children:
      bukkitircd.mode.halfop: true
      bukkitircd.mode.op: true
      bukkitircd.mode.owner: true
      bukkitircd.mode.protect: true
      bukkitircd.mode.voice: true
    description: 'Gives you all IRC user modes (+qaohv)'
  bukkitircd.mode.halfop:
    default: op
    description: 'Gives you halfop status on IRC (+h)'
  bukkitircd.mode.op:
    default: op
    description: 'Gives you op status on IRC (+o)'
  bukkitircd.mode.owner:
    default: op
    description: 'Gives you owner status on IRC (+q)'
  bukkitircd.mode.protect:
    default: op
    description: 'Gives you protected status on IRC (+a)'
  bukkitircd.mode.voice:
    default: op
    description: 'Gives you voice status on IRC (+v)'
  bukkitircd.msg:
    default: op
    description: 'Allows you to use the /ircmsg command'
  bukkitircd.oper:
    default: op
    description: 'Gives you oper status on IRC'
  bukkitircd.reload:
    default: op
    description: 'Allows you to use the /ircreload command'
  bukkitircd.reply:
    default: op
    description: 'Allows you to use the /ircreply command'
  bukkitircd.topic:
    default: op
    description: 'Allows you to use the /irctopic command'
  bukkitircd.unban:
    default: op
    description: 'Allows you to use the /ircunban command'
  bukkitircd.whois:
    default: op
    description: 'Allows you to use the /ircwhois command'